name: Deploy
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    timeout-minutes: 90
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          ref: master
      - name: Install pnpm
        uses: pnpm/action-setup@v2
      - name: Setup Node.js v16
        uses: actions/setup-node@v3
        with:
          node-version: 16.14
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - run: pnpm build
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-page # The branch the action should deploy to.
          folder: build # The folder the action should deploy.