name: PublicRelease

on:
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

jobs:
  release:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: main
          
      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Setup Node.js v16
        uses: actions/setup-node@v3
        with:
          node-version: 16.14
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build Docs
        run: pnpm run build

      - name: Build package
        run: |
          tar -czf artifacts.tar.gz -C dist .
          
      - name: Semantic release
        uses: cycjimmy/semantic-release-action@v3
        id: semantic   # Need an `id` for output variables
        with:
          extra_plugins: |
            @semantic-release/git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 传入 timer 参数，用于 DocSearch 爬虫定时器消费
      - name: Trigger docSearch scraper
        if: steps.semantic.outputs.new_release_published == 'true'
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.everest-preview+json" \
            ${{ github.event.repository.url }}/dispatches \
            -d '{"event_type": "DocSearch","client_payload": { "timer": 7200 }}'